name: Update Movie Recommendation

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write


jobs:

  update-movie:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install curl_cffi beautifulsoup4

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Update movie page
      run: |
        python3 scripts/update_movies.py

    - name: Build website
      run: |
        make all

    - name: Setup Pages
      uses: actions/configure-pages@v6

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: website

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v5